apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort           # Add this line to specify service type
  selector:
    app: mern-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002